### ISSUE TITLE
Fix warning for moment.js related to issue below

### ISSUE THREAD

**Issue by kachok** [amida-tech/orange-api#4] opened 2015-09-04 16:51 UTC
Be careful when falling back to Date constructor 

https://github.com/moment/moment/issues/1407

**Comment by jsachs** [comment] 2015-09-08 18:44
I think we should just close this. After reading through the moment ticket, we aren't doing anything wrong. The problem happens when we pass a string like `"foobar"` to moment, and it warns that if this fails in moment, the attempted calculation will be `new Date("foobar")`. This will fail anyway. The issue is for more ambiguous date strings (non-ISO) that get passed to moment. We universally use ISO dates, so I think we're good.

**Comment by jsachs** [comment] 2015-09-08 19:47
Closing, but we will have someone look into the UTC/offset issues that have to do with going to the next day.

**Closed by jsachs** 2015-09-08 19:47 UTC
